
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary
{

using System;
    using System.Collections.Generic;
    
public partial class Course
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Course()
    {

        this.Exams = new HashSet<Exam>();

        this.Students = new HashSet<Student>();

    }


    public int Id { get; private set; }

    public string InstanceName { get; private set; }

    public string Ects { get; private set; }

    public System.DateTime Schedule { get; private set; }

    public int CourseTypeId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Exam> Exams { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Student> Students { get; set; }

    public virtual Teacher Teacher { get; set; }

    public virtual CourseType CourseType { get; set; }

}

}
