//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Id { get; private set; }
        public ExamType Type { get; private set; }
        public int CourseId { get; private set; }
        public double Grade { get; private set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
