//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Types
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamAttempt
    {
        public int Id { get; private set; }
        public double Grade { get; set; }
        public int ExamId { get; private set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
