
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary
{

using System;
    using System.Collections.Generic;
    
public partial class Exam
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Exam()
    {

        this.ExamAttempts = new HashSet<ExamAttempt>();

        this.Students = new HashSet<Student>();

    }


    public int Id { get; private set; }

    public ExamType Type { get; private set; }

    public int CourseId { get; private set; }

    public bool Reexam { get; private set; }



    public virtual Course Course { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExamAttempt> ExamAttempts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Student> Students { get; set; }

}

}
